Add development and build info
bigbinary/nitroui pull request #16
Opened 2020-10-28 16:37 UTC by yedhink

Fixes #15 

@vinay0x _a

2020-10-28 16:43 UTC, vinay0x requested changes
@yedhink _a

2020-10-28 16:43 UTC, vinay0x commented on README.md
> +Once everything is done. Run `yarn build` to build new bundle files and **increment the version number** in `package.json`
```suggestion
Run `yarn build` to build new bundle files and **increment the version number** in `package.json`. Make sure to commit and push the changes to Github. In the host application, run `yarn add https://github.com/bigbinary/nitroui.git` to update it to the latest version.
```

2020-10-28 16:43 UTC, vinay0x commented on README.md
> +```
```suggestion
Running the `yarn start` command starts a CRA app which resides in `src` folder. Use this application to test out changes. Note that nothing in the `src` folder will be bundled with NitroUI.
```

2020-10-28 16:43 UTC, vinay0x commented on README.md
> +Install all the dependencies first:-
```suggestion
Install all the dependencies by running:
```

2020-10-28 16:43 UTC, vinay0x commented on README.md
> +You can create new components in the `lib/components` and add a reference to the same in `src/index.js`.
```suggestion
You can create new components in the `lib/components` and export them from`lib/index.js`.  
```

2020-10-29 05:03 UTC, yedhink commented
@vinay0x _a

Have made the requested changes.

2020-10-29 08:02 UTC, merged